[project]
name = "mcp-gateway"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["asyncpg>=0.30.0", "httpx>=0.28.1", "mcp>=1.9.2"]

[dependency-groups]
dev = ["mypy>=1.16.0", "ruff>=0.11.12"]
